work_dir: work_dir/linear_eval/modellr01
weights: work_dir/ntu60xview/model/epoch300_model.pt
ignore_weights: [encoder.fc, predictor]

train_feeder: feeder.ntu_feeder.Feeder_single
train_feeder_args:
  data_path: /data1/zengyq/dataset/data/NTU60_frame50/xview/train_position.npy
  label_path: /data1/zengyq/dataset/data/NTU-RGB-D/xview/train_label.pkl
  shear_amplitude: -1
  temperal_padding_ratio: -1
  rotate: -1
  mmap: True

test_feeder: feeder.ntu_feeder.Feeder_single
test_feeder_args:
  data_path: /data1/zengyq/dataset/data/NTU60_frame50/xview/val_position.npy
  label_path: /data1/zengyq/dataset/data/NTU-RGB-D/xview/val_label.pkl 
  shear_amplitude: -1
  temperal_padding_ratio: -1
  rotate: -1
  mmap: True

# model
model: net.skeletonsim.SkeletonSim
model_args:
  base_encoder: net.st_gcn.Model
  pretrain: False
  # feature_dim: 128
  # mlp: True
  in_channels: 3
  hidden_channels: 64 
  hidden_dim: 256
  num_class: 60
  dropout: 0.5
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'
  edge_importance_weighting: True

# optim
nesterov: False
weight_decay: 0.0
base_lr: 15.
optimizer: SGD
step: [60,80]

device: [1]
batch_size: 128
test_batch_size: 128
num_epoch: 100

# log
save_interval: -1
eval_interval: 5
