work_dir: work_dir/fine_tune/1_model300
weights: work_dir/ntu60xview/lr0.2bs512st1_4/epoch60_model.pt
ignore_weights: [online_encoder.fc,target_encoder]

# feeder
train_feeder: feeder.ntu_feeder.Feeder_single
train_feeder_args:
  data_path: data/NTU60_frame50/xview/train_position.npy
  label_path: data/NTU-RGB-D/xview/train_label.pkl 
  shear_amplitude: -1
  temperal_padding_ratio: -1
  mmap: True
test_feeder: feeder.ntu_feeder.Feeder_single
test_feeder_args:
  data_path: data/NTU60_frame50/xview/val_position.npy
  label_path: data/NTU-RGB-D/xview/val_label.pkl 
  shear_amplitude: -1
  temperal_padding_ratio: -1
  mmap: True

# model
model: net.skeletonbyol.SkeletonBYOL
model_args:
  base_encoder: net.st_gcn.Model
  pretrain: False
  in_channels: 3
  hidden_channels: 16
  hidden_dim: 256
  num_class: 60
  dropout: 0.5
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'
  edge_importance_weighting: True

# optim
nesterov: False
weight_decay: 0.0
base_lr: 0.1
optimizer: SGD
step: [80]

# training
device: [0]
batch_size: 128
test_batch_size: 128
num_epoch: 100
warm_up_epoch: 10

view: 'joint'

# log
save_interval: -1
eval_interval: 5
