work_dir: work_dir/ntu60xview/model

# feeder
train_feeder: feeder.ntu_feeder.Feeder_dual
train_feeder_args:
  data_path: /data1/zengyq/dataset/data/NTU60_frame50/xview/train_position.npy
  label_path: /data1/zengyq/dataset/data/NTU-RGB-D/xview/train_label.pkl
  shear_amplitude: 0.5
  temperal_padding_ratio: 6
  rotate: 1
  mmap: True

# model
model: net.skeletonsim.SkeletonSim
model_args:
  base_encoder: net.st_gcn.Model
  pretrain: True
  feature_dim: 128
  mlp: True
  in_channels: 3
  hidden_channels: 64 
  hidden_dim: 256
  num_class: 60
  dropout: 0.5
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'
  edge_importance_weighting: True

# optim
nesterov: False
weight_decay: 1e-4
base_lr: 0.05
optimizer: SGD
# step: [250]
cos: True
warm_up_epoch: 10

# training
device: [0]
batch_size: 128
num_epoch: 300
start_epoch: 0

# log
save_interval: 10
eval_interval: -1


# model: net.skeletonsim. SkeletonSim
# model_args:
#   base_encoder: net.agcn.Model
#   pretrain: True
#   feature_dim: 128
#   mlp: True
#   in_channels: 3
#   hidden_channels: 64 
#   hidden_dim: 256
#   num_class: 60
#   dropout: 0.5
#   graph_args:
#     layout: 'ntu-rgb+d'
#     strategy: 'spatial'
#   edge_importance_weighting: True